# SEComplexityDemo
version: 2.1

jobs:
    build:
      docker:
        - image: srcml/ubuntu_x86_64_base
      steps:
        - checkout
        - run: apt-get update
        - run: mkdir build
        - run: cd build && cmake -DCMAKE_BUILD_TYPE=Release .. -G Ninja
        - run: cd build && ninja && ninja install && ldconfig
        - run: cd build && ninja run
